export const countries = [
    { title: 'ar', name: 'Argentina' },
    { title: 'au', name: 'Australia' },
    { title: 'at', name: 'Austria' },
    { title: 'be', name: 'Belgium' },
    { title: 'br', name: 'Brazil' },
    { title: 'bg', name: 'Bulgaria' },
    { title: 'ca', name: 'Canada' },
    { title: 'cn', name: 'China' },
    { title: 'co', name: 'Columbia' },
    { title: 'cu', name: 'Cuba' },
    { title: 'cz', name: 'Czech Republic' },
    { title: 'eg', name: 'Egypt' },
    { title: 'fr', name: 'France' },
    { title: 'de', name: 'Germany' },
    { title: 'gr', name: 'Greece' },
    { title: 'hk', name: 'Hong Kong' },
    { title: 'hu', name: 'Hungary' },
    { title: 'in', name: 'India' },
    { title: 'id', name: 'Indonesia' },
    { title: 'ie', name: 'Ireland' },
    { title: 'il', name: 'Isreal' },
    { title: 'it', name: 'Italy' },
    { title: 'jp', name: 'Japan' },
    { title: 'lv', name: 'Latvia' },
    { title: 'lt', name: 'Lithuania' },
    { title: 'my', name: 'Malaysia' },
    { title: 'mx', name: 'Mexico' },
    { title: 'ma', name: 'Morocco' },
    { title: 'nl', name: 'Netherlands' },
    { title: 'nz', name: 'New Zealand' },
    { title: 'ng', name: 'Nigeria' },
    { title: 'no', name: 'Norway' },
    { title: 'ph', name: 'Philippines' },
    { title: 'pl', name: 'Poland' },
    { title: 'ro', name: 'Romania' },
    { title: 'ru', name: 'Russia' },
    { title: 'sa', name: 'Saudi Arabia' },
    { title: 'rs', name: 'Serbia' },
    { title: 'sg', name: 'Singapore' },
    { title: 'sk', name: 'Slovakia' },
    { title: 'si', name: 'Slovenia' },
    { title: 'za', name: 'South Africa' },
    { title: 'kr', name: 'South Korea' },
    { title: 'se', name: 'Sweden' },
    { title: 'ch', name: 'Switzerland' },
    { title: 'tw', name: 'Taiwan' },
    { title: 'th', name: 'Thailand' },
    { title: 'tr', name: 'Turkey' },
    { title: 'ae', name: 'UAE' },
    { title: 'ua', name: 'Ukraine' },
    { title: 'gb', name: 'United Kingdom' },
    { title: 'us', name: 'United States' },
    { title: 've', name: 'Venuzuela' }
];
